### ISSUE TITLE
Fix display of point icons

### ISSUE THREAD

**Issue by nupoormonani** [allthesignals/cityxcity#189]
Investment badge PNGs are not showing in many places. This is a screenshot from Haverhill. 

![image](https://user-images.githubusercontent.com/19911108/37247027-a849c3fa-2482-11e8-941b-80ea48c9ddad.png)

**Comment by allthesignals** [comment]
This may be a data issue - some data opoints don't have consistent naming

**Comment by allthesignals** [comment]
Most of the icons are in working order now. There are some remaining and they are data issues. What's happened is that the icon names are derived from their category names. The app will look up an icon by name. For some reason, however, the category of some icons include a `/`, so the app looks for a filename with a subdirectory like this:
`/images/icons/investments/tdi/planning/strategy.png`

The icon I have for this ^ is `planning-or-strategy.png`, so the data should be updated.

**Comment by allthesignals** [comment]
Second, I don't have an `industrial.png` icon for some reason 🤔 can't seem to find it. Thanks.

**Comment by nupoormonani** [comment]
OK, I understand that this is a data issue. @laurabarrett I believe you have the keys to Fieldbook. Could you make this change at your end?

**Comment by nupoormonani** [comment]
@allthesignals "Industrial" is not a place or investment type. Could you clarify where "industrial.png" is needed?

**Comment by ericyoungberg** [comment]
@nupoormonani @laurabarrett It appears that the "Industrial" place type is only used for one record. That record can be found here: https://fieldbook.com/sheets/594edf6d08168d0300211bcc?query=place_id%3A130.

As Matt said, if the place type is changed to a valid value, then this part of the issue will be resolved once I remove the filter from the codebase.

Otherwise, since the _industrial.png_ image isn't found in the _PNG Symbols.zip_ file that was sent over WeTransfer, I quickly cooked up one that we could use: 
![feature - industrial](https://user-images.githubusercontent.com/6749126/39436034-e311d53a-4c6a-11e8-8f6c-d42a572e1746.png)

**Comment by ericyoungberg** [comment]
In addition, I've noticed that the "Mixed Use" icon is identical to the "Temporary" icon instead of the icon with a plain, white circle inside which is used in the mockups; is this intentional or should I fix that as well?

**Comment by nupoormonani** [comment]
Eric,

1. This seems to have been classified as "industrial" in error. Per the
latest data structure and style guide, "industrial" should not be a place
type. We can change it to "mixed-use" unless @laurabarrett has a different
preference.
2. The blank circle icon was a placeholder for "mixed-use". You can go
ahead and change it to the PNG attached here instead.

Thanks for checking in!

Nupoor Monani

Utile
115 Kingston St., Boston, MA 02111
(617) 423-7200 | utiledesign.com
