### ISSUE TITLE
Change "Cityxcity" in staging URL and page name to "Block x Block"

### ISSUE THREAD

**Issue by nupoormonani** [allthesignals/cityxcity#199]
![image](https://user-images.githubusercontent.com/19911108/37974643-66521822-31ab-11e8-8491-4d425da718bb.png)

**Comment by ericyoungberg** [comment]
Once https://github.com/MAPC/cityxcity/commit/cbf0a9f92d627b2f76292054bcadfb147ab3e37e is merged in, the browser tab will display "Block x Block" instead of "Cityxcity", but we can't change the staging URL without changing the name of the repository.

Changing the name of the repository may have longterm side effects once Github is no longer caching the redirect. This only means that any links currently pointing to https://github.com/allthesignals/cityxcity and https://allthesignals.github.io/cityxcity will break in the near future. If no one has any objections or concerns about that, then Matt will have to change the repo name.

@allthesignals @nupoormonani @arouault

**Comment by allthesignals** [comment]
@ericyoungberg happy to change the repository if you'd like, you could also move the staging to mapc:  https://mapc.github.io/blockxblock.

Let me know which you prefer.

**Comment by ericyoungberg** [comment]
@allthesignals maybe once the current development phase is done. I think between the issues being hosted here and it still being a fresh fork on our end, it might cause minor chaos.

**Comment by nupoormonani** [comment]
​Eric and Matt, it's fine to leave the URL as is for now, as long as the
title on the browser reads "Block x Block" Thanks!​

Nupoor Monani

Utile
115 Kingston St., Boston, MA 02111
(617) 423-7200 | utiledesign.com

**Comment by ericyoungberg** [comment]
Closed by 6c319a24b63bfc23837df842aed317d5c4375d58
