### ISSUE TITLE
Operational filters

### ISSUE THREAD

**Issue by laurabarrett** [allthesignals/cityxcity#204]
Just clarifying that one element of the MVP is operational filters. Based on a conversation with Anne, if the timeline function is not able to be included as a slider then we would need to include some timeline function as a filter to be able to show snapshots of time.  @nupoormonani - would Utile be able to provide design direction for this task if needed? Thank you - LB

**Comment by ericyoungberg** [comment]
![time-machine-mock](https://user-images.githubusercontent.com/6749126/39723320-8148c62a-5213-11e8-90aa-ef9c3dacf4fb.jpg)
 
Time Machine segment will be inside of a block down at the left hand corner of the map, next to the filter panel instead of next to the filter panel title.

**Comment by nupoormonani** [comment]
- When the date is set to "02 2018" what it is showing us? All points open as of 2/01/2018 or all points open on any date during 02/2018?

- Let's move the time filter to the bottom left corner of the map as Alicia suggested. 

- Instead of "Time machine" can we change the title to "Change over time"?

- Can you incorporate a down-arrow in the design of the buttons so it clearly looks like a drop-down box? You could use the same style arrow as the "city" drop down in the header.

**Comment by nupoormonani** [comment]
cc @laurabarrett

**Comment by ericyoungberg** [comment]
The date specifies the current temporal state of the dataset; if the time is "02 2018", then it will show the dataset as it was in 02/28/2018. We must expand to the last day of the month otherwise we wouldn't be showing the activity that occurred in the month selected by the user. 

We can change the title from "Time Machine" to something different, but "Change over time" would be misleading. Since there is only one temporal boundary, we can't define a range to change over. Luckily, titles are easy to change so I can continue while we flesh the title out. Keeping the notion of time in the header seems essential. What if we used "Historical Data" or "Historical Snapshot"?

I can incorporate a down-arrow much like the one used in the "city" drop down.

**Comment by nupoormonani** [comment]
@ericyoungberg: Yes, makes sense to show all activity throughout the month. Thanks for clarifying. 

Instead of "Time machine" or "Change over time," I propose making the title a call to action. Let's try "Pick a month and year below to see change in TDI activity." Calls attention to the functionality and avoids any confusion with the yet-to-be-built time slider. cc @laurabarrett let us know if you want to go in a different direction.   

OK on the drop-down arrow.

**Comment by laurabarrett** [comment]
I agree about change over time as being misleading as a label (even though its how the team was referring to the feature). I actually don't mind "Time Machine" (or "Timeline Snapshot"?) ... "historical" to me lays an expectation that the data goes further back than it does. 

I think time may be too tight to play with how a call to action would fit on the panel (vs the short phrase) so that's why I'd avoid that. An info "i" circle with the call to action visible when you hover would be good if doable, but that's a "nice to have"

ditto: ok on the drop down. 

thanks!

**Comment by laurabarrett** [comment]
Yes, drop down serves the function of the slider (maybe that changes in future scopes but drop down for now and forseeable future)

I'm good with "Set Date"

thanks everyone for weighing in!

**Comment by nupoormonani** [comment]
@arouault @laurabarrett OK, "set Date" works for me. Re. the time slider, my understanding was that this is still on the table for a future scope/maintenance scope. @laurabarrett are we going in a different direction?

**Comment by laurabarrett** [comment]
Sure, it's still on the table but maybe that's something we determine after using the tool a bit. The maintenance scope is stacking up now! We'll definitely have to prioritize.

**Comment by nupoormonani** [comment]
@laurabarrett Gotcha, thanks!
