### ISSUE TITLE
Update text for "Data Info" section of the home page

### ISSUE THREAD

**Issue by nupoormonani** [allthesignals/cityxcity#219]
@laurabarrett please provide the text content. You can paste it here. Thanks!

**Comment by laurabarrett** [comment]
[About Block x Block and Data Info 180508.pdf](https://github.com/allthesignals/cityxcity/files/1985187/About.Block.x.Block.and.Data.Info.180508.pdf)

Data info text is included on the second page of the attached PDF

**Comment by nupoormonani** [comment]
Awesome, thanks!

Nupoor Monani

Utile
115 Kingston St., Boston, MA 02111
(617) 423-7200 | utiledesign.com

**Comment by nupoormonani** [comment]
@ericyoungberg I pasted the content into the HTML code found here: https://github.com/allthesignals/cityxcity/blob/develop/app/templates/index.hbs#L35 and hit "commit changes," yet the website doesn't seem to have updated. Do you know why this is? Is there any action needed at your end to push this change through? Thanks! cc @laurabarrett

**Comment by ericyoungberg** [comment]
Yeah, I have to deploy any changes to the staging server. The reason why this is a two step process now is because we are no longer hooked to Github's minimal staging environment called Github Pages; the code is now on a secure server hosted and managed by MAPC. 

I can do intermediary deploys to staging throughout the week if requested. Otherwise, I'll be pushing everything to staging by Friday morning each week so we can review progress and decide/gauge the work the needs to be performed the week that follows.

**Comment by nupoormonani** [comment]
Thanks Eric, I understand. My concern is that the text alignment in this
section will not work for the Data Info content, which is a bulleted list.
Can we change the the formatting of this text so it is all left-aligned
instead?

Nupoor Monani

Utile
115 Kingston St., Boston, MA 02111
(617) 423-7200 | utiledesign.com

**Comment by laurabarrett** [comment]
Pushing Friday sounds OK but I just want to flag what you mentioned about "each week." We're still shooting for an MVP by this Friday correct? 

Pushing e/ week during maintenance or subsequent scopes sounds good though!

**Comment by ericyoungberg** [comment]
Closed by https://github.com/allthesignals/cityxcity/commit/f6d0f3212d7e9c100a4c3b6f4bd88cfa7f5714c1
